spring.profiles.active: 'production'
---
spring:
  config.activate.on-profile: 'production'
  datasource:

    # Ссылка на базу данных в формате JDBC
    url: jdbc:mysql://localhost:3306/warehouse

    # Логин для доступа к базе данных
    username: root

    # Пароль для доступа к базе данны
    password:

    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: none
    open-in-view: true
  sql.init:
      mode: always
      schema-locations: classpath*:db/mysql/schema.sql
  servlet.multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
