spring:
  datasource:
#    url: jdbc:h2:file:./src/main/resources/database/warehouse;AUTO_SERVER=TRUE
#    url: jdbc:postgresql://localhost:5432/hr_manager
    url: jdbc:mysql://localhost:3306/warehouse
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
#    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    generate-ddl: true
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
