spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/database/warehouse;AUTO_SERVER=TRUE
#    url: jdbc:postgresql://localhost:5432/hr_manager
    username: sa
    password: 1
    driverClassName: org.h2.Driver
#    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
